using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using NUnit.Framework;
using UnityEditor;
using UnityEngine;
using UnityEngine.Animations;
using UnityEngine.Playables;
using UnityEngine.TestTools;
using UnityGLTF;
using UnityGLTF.Loader;

/// <summary>
/// Import tests for animated and rigged assets: generic root motion, humanoid avatars and how both interact with
/// "Remove Empty Root Objects". The test assets are generated by Tests/Assets/Rigs/Generator~/generate-rig-test-assets.js.
/// Each asset is copied into a temporary folder in Assets, so changing import settings never touches the package's .meta files.
/// Roundtrip tests (import, export, import) are in RigImportTests.Roundtrip.cs.
/// </summary>
public partial class RigImportTests
{
	private const string SourceFolder = "Packages/org.khronos.unitygltf/Tests/Assets/Rigs";
	private const string TempFolder = "Assets/UnityGLTFTests_Rigs";

	private const string RootMotionEmptyRoot = "RootMotion_EmptyRoot.glb";
	private const string RootMotionAnimatedRoot = "RootMotion_AnimatedRoot.glb";
	private const string StaticNoAnimation = "Static_NoAnimation.glb";
	private const string HumanoidArmature = "Humanoid_Armature.glb";
	private const string HumanoidMixamo = "Humanoid_Mixamo.glb";
	private const string HumanoidAPose = "Humanoid_APose.glb";
	private const string HumanoidUnrealNames = "Humanoid_UnrealNames.glb";
	// Humanoid_Armature with a "Prop" below RightHand: Walk also spins it, PropOnly only moves the prop
	private const string HumanoidProps = "Humanoid_Props.glb";

	[OneTimeSetUp]
	public void OneTimeSetUp()
	{
		if (!AssetDatabase.IsValidFolder(TempFolder))
			AssetDatabase.CreateFolder("Assets", Path.GetFileName(TempFolder));
	}

	[OneTimeTearDown]
	public void OneTimeTearDown()
	{
		AssetDatabase.DeleteAsset(TempFolder);
	}

	#region Helpers

	private static void CopyTestAsset(string file, string path)
	{
		var source = FileUtil.GetPhysicalPath($"{SourceFolder}/{file}");
		Assert.IsTrue(File.Exists(source), $"Test asset not found: {source}");
		File.Copy(source, path, true);
		AssetDatabase.ImportAsset(path, ImportAssetOptions.ForceSynchronousImport);
	}

	private static string Import(string file, AnimationMethod method, string rootNodeName = "", bool removeEmptyRoots = true, bool humanoidFlip = false, bool readWrite = true)
	{
		var path = $"{TempFolder}/{file}";
		if (!File.Exists(path))
			CopyTestAsset(file, path);

		Reimport(path, method, rootNodeName, removeEmptyRoots, humanoidFlip, readWrite);
		return path;
	}

	/// <summary>
	/// Sets the import settings of an asset in the temp folder and reimports it.
	/// </summary>
	internal static void Reimport(string path, AnimationMethod method, string rootNodeName = "", bool removeEmptyRoots = true, bool humanoidFlip = false, bool readWrite = true)
	{
		var importer = AssetImporter.GetAtPath(path) as GLTFImporter;
		Assert.IsNotNull(importer, $"{path} is not imported with the {nameof(GLTFImporter)}");

		var so = new SerializedObject(importer);
		so.FindProperty("_importAnimations").intValue = (int)method;
		so.FindProperty("_nonHumanoidRootNodeName").stringValue = rootNodeName;
		so.FindProperty("_removeEmptyRootObjects").boolValue = removeEmptyRoots;
		so.FindProperty("_mecanimHumanoidFlip").boolValue = humanoidFlip;
		so.FindProperty("_readWriteEnabled").boolValue = readWrite;
		so.ApplyModifiedPropertiesWithoutUndo();
		importer.SaveAndReimport();
	}

	internal static GameObject LoadModel(string path)
	{
		var model = AssetDatabase.LoadAssetAtPath<GameObject>(path);
		Assert.IsTrue(model, $"No model imported at {path}");
		return model;
	}

	internal static Avatar LoadAvatar(string path) => AssetDatabase.LoadAllAssetsAtPath(path).OfType<Avatar>().SingleOrDefault();

	internal static AnimationClip[] LoadClips(string path) => AssetDatabase.LoadAllAssetsAtPath(path).OfType<AnimationClip>().ToArray();

	private static void AssertClipBindingsResolve(string path)
	{
		var model = LoadModel(path);
		foreach (var clip in LoadClips(path))
		foreach (var binding in AnimationUtility.GetCurveBindings(clip))
		{
			var target = string.IsNullOrEmpty(binding.path) ? model.transform : model.transform.Find(binding.path);
			Assert.IsTrue(target, $"Clip \"{clip.name}\" animates \"{binding.path}\", which doesn't exist below \"{model.name}\"");
		}
	}

	#endregion

	#region Generic

	[Test]
	public void Static_Mecanim_WithoutRootNode_CreatesNoAvatar()
	{
		var path = Import(StaticNoAnimation, AnimationMethod.Mecanim);
		Assert.IsNull(LoadAvatar(path), "A static model should not get an unused avatar");
	}

	[TestCase(RootMotionEmptyRoot)]
	[TestCase(HumanoidArmature)]
	public void DefaultSettings_AnimatedFile_Imports(string file)
	{
		// A fresh copy, so it's imported with default settings
		var path = $"{TempFolder}/Default_{file}";
		CopyTestAsset(file, path);

		LoadModel(path);
		Assert.IsNotNull(LoadAvatar(path));
		Assert.IsNotEmpty(LoadClips(path));
	}

	[Test]
	public void Static_Mecanim_WithRootNode_CreatesGenericAvatar()
	{
		// Removing empty roots makes "Body" the root of this file, so the root node is its child "Nose"
		var path = Import(StaticNoAnimation, AnimationMethod.Mecanim, "Nose");
		var avatar = LoadAvatar(path);
		Assert.IsNotNull(avatar, "A root node is set, so the avatar is needed for root motion with clips from other files");
		Assert.IsTrue(avatar.isValid);
		Assert.IsFalse(avatar.isHuman);
	}

	[TestCase(RootMotionEmptyRoot, true)]
	[TestCase(RootMotionEmptyRoot, false)]
	[TestCase(RootMotionAnimatedRoot, true)]
	[TestCase(RootMotionAnimatedRoot, false)]
	public void Generic_Mecanim_CreatesGenericAvatarAndClips(string file, bool removeEmptyRoots)
	{
		var path = Import(file, AnimationMethod.Mecanim, removeEmptyRoots: removeEmptyRoots);

		var avatar = LoadAvatar(path);
		Assert.IsNotNull(avatar);
		Assert.IsTrue(avatar.isValid);
		Assert.IsFalse(avatar.isHuman);

		var animator = LoadModel(path).GetComponent<Animator>();
		Assert.IsTrue(animator, "Mecanim import should add an Animator to the root");
		Assert.AreEqual(avatar, animator.avatar);

		CollectionAssert.AreEquivalent(new[] { "WalkForward", "TurnLeft" }, LoadClips(path).Select(c => c.name));
		AssertClipBindingsResolve(path);
	}

	[TestCase(RootMotionEmptyRoot, true)]
	[TestCase(RootMotionEmptyRoot, false)]
	[TestCase(RootMotionAnimatedRoot, true)]
	[TestCase(RootMotionAnimatedRoot, false)]
	public void Generic_Mecanim_WithRootNode_EnablesApplyRootMotion(string file, bool removeEmptyRoots)
	{
		var path = Import(file, AnimationMethod.Mecanim, "Root", removeEmptyRoots);

		var animator = LoadModel(path).GetComponent<Animator>();
		Assert.IsTrue(animator);
		Assert.IsTrue(animator.applyRootMotion, "Apply Root Motion should be enabled (and survive removing empty roots)");
		Assert.AreEqual(LoadAvatar(path), animator.avatar);
		AssertClipBindingsResolve(path);
	}

	[Test]
	public void Generic_RemoveEmptyRoots_StripsEmptyRootButKeepsAnimatedNode()
	{
		var path = Import(RootMotionEmptyRoot, AnimationMethod.Mecanim, "Root");
		var model = LoadModel(path);
		Assert.IsTrue(model.transform.Find("Root"), "The empty root above the animated node should be removed");
		Assert.IsTrue(model.GetComponent<Animator>(), "The Animator should be re-added on the new root");
	}

	[Test]
	public void Generic_KeepEmptyRoots_KeepsHierarchy()
	{
		var path = Import(RootMotionEmptyRoot, AnimationMethod.Mecanim, "Root", removeEmptyRoots: false);
		Assert.IsTrue(LoadModel(path).transform.Find("Character/Root"));
	}

	[Test]
	public void Generic_AnimatedTopNode_IsNotStripped()
	{
		var path = Import(RootMotionAnimatedRoot, AnimationMethod.Mecanim, "Root");
		Assert.IsTrue(LoadModel(path).transform.Find("Root"), "An animated node must never be removed as an empty root");
	}

	[Test]
	public void Generic_UnknownRootNode_StillImports()
	{
		// Logs an import warning instead of AvatarBuilder's error, so the test doesn't fail on an unexpected error log
		var path = Import(RootMotionEmptyRoot, AnimationMethod.Mecanim, "DoesNotExist");
		var avatar = LoadAvatar(path);
		Assert.IsNotNull(avatar);
		Assert.IsTrue(avatar.isValid);
	}

	[Test]
	public void Generic_Legacy_CreatesNoAvatar()
	{
		var path = Import(RootMotionEmptyRoot, AnimationMethod.Legacy, "Root");
		var model = LoadModel(path);
		Assert.IsNull(LoadAvatar(path));
		Assert.IsTrue(model.GetComponent<Animation>());
		Assert.IsFalse(model.GetComponent<Animator>());
	}

	[Test]
	public void Generic_None_CreatesNoAvatarAndNoAnimations()
	{
		var path = Import(RootMotionEmptyRoot, AnimationMethod.None, "Root");
		var model = LoadModel(path);
		Assert.IsNull(LoadAvatar(path));
		Assert.IsFalse(model.GetComponent<Animator>());
		Assert.IsFalse(model.GetComponent<Animation>());
		Assert.IsEmpty(LoadClips(path));
	}

	#endregion

	#region Humanoid

	[TestCase(HumanoidArmature, true)]
	[TestCase(HumanoidArmature, false)]
	[TestCase(HumanoidMixamo, true)]
	[TestCase(HumanoidMixamo, false)]
	[TestCase(HumanoidAPose, true)]
	[TestCase(HumanoidUnrealNames, true)]
	public void Humanoid_CreatesHumanAvatar(string file, bool removeEmptyRoots)
	{
		var path = Import(file, AnimationMethod.MecanimHumanoid, removeEmptyRoots: removeEmptyRoots);

		var avatar = LoadAvatar(path);
		Assert.IsNotNull(avatar);
		Assert.IsTrue(avatar.isValid);
		Assert.IsTrue(avatar.isHuman);

		var animator = LoadModel(path).GetComponent<Animator>();
		Assert.IsTrue(animator);
		Assert.AreEqual(avatar, animator.avatar);
		Assert.IsTrue(animator.applyRootMotion, "Apply Root Motion should be enabled (and survive removing empty roots)");

		CollectionAssert.AreEquivalent(new[] { "Walk", "Idle" }, LoadClips(path).Select(c => c.name));
		AssertClipBindingsResolve(path);
	}

	[TestCase(HumanoidArmature, "Hips", "LeftUpperArm", "RightToes")]
	[TestCase(HumanoidMixamo, "mixamorig:Hips", "mixamorig:LeftArm", "mixamorig:RightToeBase")]
	public void Humanoid_MapsAllRequiredBones(string file, string hips, string leftUpperArm, string rightToes)
	{
		var path = Import(file, AnimationMethod.MecanimHumanoid);
		var human = LoadAvatar(path).humanDescription.human;
		var mapping = human.ToDictionary(b => b.humanName, b => b.boneName);

		for (var i = 0; i < HumanTrait.BoneCount; i++)
		{
			if (!HumanTrait.RequiredBone(i)) continue;
			Assert.IsTrue(mapping.ContainsKey(HumanTrait.BoneName[i]), $"Required bone {HumanTrait.BoneName[i]} is not mapped");
		}

		Assert.AreEqual(hips, mapping["Hips"]);
		Assert.AreEqual(leftUpperArm, mapping["LeftUpperArm"]);
		Assert.AreEqual(rightToes, mapping["RightToes"]);
	}

	[Test]
	public void Humanoid_UnknownBoneNames_AreMappedAutomatically()
	{
		// Unreal style names aren't in UnityGLTF's name dictionary, so Unity's auto mapping has to find them
		var path = Import(HumanoidUnrealNames, AnimationMethod.MecanimHumanoid);
		var avatar = LoadAvatar(path);
		Assert.IsNotNull(avatar, "No valid human avatar for a rig with Unreal bone names");
		var mapping = avatar.humanDescription.human.ToDictionary(b => b.humanName, b => b.boneName);

		for (var i = 0; i < HumanTrait.BoneCount; i++)
		{
			if (!HumanTrait.RequiredBone(i)) continue;
			Assert.IsTrue(mapping.ContainsKey(HumanTrait.BoneName[i]), $"Required bone {HumanTrait.BoneName[i]} is not mapped");
		}

		Assert.AreEqual("pelvis", mapping["Hips"]);
		Assert.AreEqual("upperarm_l", mapping["LeftUpperArm"]);
		Assert.AreEqual("lowerarm_r", mapping["RightLowerArm"]);
		Assert.AreEqual("thigh_l", mapping["LeftUpperLeg"]);
		Assert.AreEqual("calf_r", mapping["RightLowerLeg"]);
	}

	[TestCase(HumanoidArmature)]
	[TestCase(HumanoidMixamo)]
	[TestCase(HumanoidAPose)]
	[TestCase(HumanoidUnrealNames)]
	public void Humanoid_HasSkeletonPose(string file)
	{
		var path = Import(file, AnimationMethod.MecanimHumanoid);
		var skeleton = LoadAvatar(path).humanDescription.skeleton;
		Assert.IsNotEmpty(skeleton, "The avatar should store the skeleton (T-)pose");
	}

	/// <summary>
	/// Direction from the upper to the lower arm, in the skeleton pose stored in the avatar (or in the model's own pose).
	/// </summary>
	private static Vector3 ArmDirection(string path, string side, bool useAvatarSkeleton)
	{
		var avatar = LoadAvatar(path);
		var instance = Object.Instantiate(LoadModel(path));
		try
		{
			var transforms = instance.GetComponentsInChildren<Transform>(true).GroupBy(t => t.name).ToDictionary(g => g.Key, g => g.First());
			if (useAvatarSkeleton)
			{
				foreach (var bone in avatar.humanDescription.skeleton)
				{
					if (!transforms.TryGetValue(bone.name, out var t) || t == instance.transform) continue;
					t.localPosition = bone.position;
					t.localRotation = bone.rotation;
				}
			}

			var mapping = avatar.humanDescription.human.ToDictionary(b => b.humanName, b => b.boneName);
			var upperArm = transforms[mapping[side + "UpperArm"]];
			var lowerArm = transforms[mapping[side + "LowerArm"]];
			return (lowerArm.position - upperArm.position).normalized;
		}
		finally
		{
			Object.DestroyImmediate(instance);
		}
	}

	[TestCase("Left")]
	[TestCase("Right")]
	public void Humanoid_APose_IsCorrectedToTPose(string side)
	{
		var path = Import(HumanoidAPose, AnimationMethod.MecanimHumanoid);

		var modelArm = ArmDirection(path, side, useAvatarSkeleton: false);
		Assert.Less(modelArm.y, -0.5f, $"Test asset should be in A-pose, but the {side} arm points {modelArm}");

		var avatarArm = ArmDirection(path, side, useAvatarSkeleton: true);
		Assert.AreEqual(0f, avatarArm.y, 0.1f, $"The avatar's skeleton pose should be a T-pose, but the {side} arm points {avatarArm}");
	}

	[TestCase(HumanoidArmature)]
	[TestCase(HumanoidAPose)]
	[TestCase(HumanoidUnrealNames)]
	public void Humanoid_ReadWriteDisabled_CreatesHumanAvatar(string file)
	{
		// Meshes aren't readable during avatar setup then, so bone weights can't be used to find the skeleton
		var path = Import(file, AnimationMethod.MecanimHumanoid, readWrite: false);
		var avatar = LoadAvatar(path);
		Assert.IsNotNull(avatar);
		Assert.IsTrue(avatar.isValid);
		Assert.IsTrue(avatar.isHuman);
	}

	[Test]
	public void Humanoid_FlipForward_CreatesValidAvatar()
	{
		var path = Import(HumanoidArmature, AnimationMethod.MecanimHumanoid, humanoidFlip: true);
		var avatar = LoadAvatar(path);
		Assert.IsNotNull(avatar);
		Assert.IsTrue(avatar.isValid);
		Assert.IsTrue(avatar.isHuman);
	}

	[Test]
	public void Humanoid_ImportedAsGeneric_CreatesGenericAvatar()
	{
		var path = Import(HumanoidArmature, AnimationMethod.Mecanim, "Hips");
		var avatar = LoadAvatar(path);
		Assert.IsNotNull(avatar);
		Assert.IsTrue(avatar.isValid);
		Assert.IsFalse(avatar.isHuman);
		Assert.IsTrue(LoadModel(path).GetComponent<Animator>().applyRootMotion);
	}

	#endregion

	#region Root motion playback

	/// <summary>
	/// Plays a clip on an instance of the imported model and returns how far the instance itself moved.
	/// </summary>
	private static (Vector3 instanceOffset, Vector3 rootNodeOffset) PlayClip(string path, string clipName, float seconds)
	{
		var (instanceOffset, rootNodeOffset, _) = PlayClipWithRotation(path, clipName, seconds);
		return (instanceOffset, rootNodeOffset);
	}

	private static (Vector3 instanceOffset, Vector3 rootNodeOffset, Quaternion instanceRotation) PlayClipWithRotation(string path, string clipName, float seconds)
	{
		var clip = LoadClips(path).Single(c => c.name == clipName);
		var instance = Object.Instantiate(LoadModel(path));
		var graph = PlayableGraph.Create("RigImportTests");
		try
		{
			var animator = instance.GetComponent<Animator>();
			Assert.IsTrue(animator);

			// Search the whole hierarchy, since the depth of "Root" depends on "Remove Empty Root Objects"
			var rootNode = instance.GetComponentsInChildren<Transform>(true).FirstOrDefault(t => t.name == "Root");
			var rootNodeStart = rootNode ? rootNode.localPosition : Vector3.zero;
			var instanceStart = instance.transform.position;

			graph.SetTimeUpdateMode(DirectorUpdateMode.Manual);
			var output = AnimationPlayableOutput.Create(graph, "Animation", animator);
			output.SetSourcePlayable(AnimationClipPlayable.Create(graph, clip));
			graph.Play();

			const float step = 0.1f;
			for (var t = 0f; t < seconds; t += step)
				graph.Evaluate(step);

			return (instance.transform.position - instanceStart, rootNode ? rootNode.localPosition - rootNodeStart : Vector3.zero, instance.transform.rotation);
		}
		finally
		{
			graph.Destroy();
			Object.DestroyImmediate(instance);
		}
	}

	[TestCase(RootMotionEmptyRoot, true)]
	[TestCase(RootMotionEmptyRoot, false)]
	[TestCase(RootMotionAnimatedRoot, true)]
	[TestCase(RootMotionAnimatedRoot, false)]
	public void Generic_WithRootNode_ClipsHaveMotionCurves(string file, bool removeEmptyRoots)
	{
		var path = Import(file, AnimationMethod.Mecanim, "Root", removeEmptyRoots);
		foreach (var clip in LoadClips(path))
			Assert.IsTrue(clip.hasMotionCurves, $"Clip \"{clip.name}\" animates the root node, so it needs root motion curves");
	}

	[TestCase(RootMotionEmptyRoot)]
	[TestCase(RootMotionAnimatedRoot)]
	public void Generic_WithRootNode_MotionCurvesOnlyContainTheClipsOwnMotion(string file)
	{
		// TurnLeft only rotates the root node. Its motion curves must not pick up the position of another clip
		// that was sampled before it.
		var path = Import(file, AnimationMethod.Mecanim, "Root");
		var turnLeft = LoadClips(path).Single(c => c.name == "TurnLeft");
		foreach (var axis in new[] { "x", "y", "z" })
		{
			var curve = AnimationUtility.GetEditorCurve(turnLeft, EditorCurveBinding.FloatCurve("", typeof(Animator), "MotionT." + axis));
			Assert.IsNotNull(curve, $"MotionT.{axis} is missing");
			Assert.IsTrue(curve.keys.All(k => Mathf.Abs(k.value) < 0.001f), $"TurnLeft doesn't move, but MotionT.{axis} has values up to {curve.keys.Max(k => Mathf.Abs(k.value))}");
		}
	}

	[Test]
	public void Generic_WithoutRootNode_ClipsHaveNoMotionCurves()
	{
		var path = Import(RootMotionEmptyRoot, AnimationMethod.Mecanim);
		foreach (var clip in LoadClips(path))
			Assert.IsFalse(clip.hasMotionCurves, $"Clip \"{clip.name}\" shouldn't get root motion curves without a root node");
	}

	[TestCase(RootMotionEmptyRoot, true)]
	[TestCase(RootMotionEmptyRoot, false)]
	[TestCase(RootMotionAnimatedRoot, true)]
	[TestCase(RootMotionAnimatedRoot, false)]
	public void Generic_WithRootNode_RootMotionMovesInstance(string file, bool removeEmptyRoots)
	{
		var path = Import(file, AnimationMethod.Mecanim, "Root", removeEmptyRoots);
		var (instanceOffset, rootNodeOffset) = PlayClip(path, "WalkForward", 0.9f);

		// WalkForward moves the Root node 1.5m in 1s; with root motion that movement is applied to the instance instead
		var horizontal = Vector3.ProjectOnPlane(instanceOffset, Vector3.up).magnitude;
		Assert.AreEqual(1.35f, horizontal, 0.1f, $"Root motion should move the instance, but it moved {instanceOffset}");
		Assert.Less(Vector3.ProjectOnPlane(rootNodeOffset, Vector3.up).magnitude, 0.01f, "The root node itself should stay in place");
	}

	[Test]
	public void Generic_WithRootNode_RootMotionRotatesInstance()
	{
		var path = Import(RootMotionEmptyRoot, AnimationMethod.Mecanim, "Root");
		var (_, _, rotation) = PlayClipWithRotation(path, "TurnLeft", 0.9f);

		// TurnLeft turns the Root node 90° in 1s (the direction depends on the glTF -> Unity axis conversion)
		Assert.AreEqual(81f, Quaternion.Angle(Quaternion.identity, rotation), 5f, $"Root motion should rotate the instance, but it is at {rotation.eulerAngles}");
	}

	[Test]
	public void Generic_WithoutRootNode_InstanceStaysInPlace()
	{
		var path = Import(RootMotionEmptyRoot, AnimationMethod.Mecanim);
		var (instanceOffset, rootNodeOffset) = PlayClip(path, "WalkForward", 0.9f);

		Assert.Less(instanceOffset.magnitude, 0.01f, $"Without a root node the instance shouldn't move, but it moved {instanceOffset}");
		Assert.Greater(Vector3.ProjectOnPlane(rootNodeOffset, Vector3.up).magnitude, 0.5f, "The Root node itself should be animated");
	}

	#endregion

	#region Humanoid clips

	// https://github.com/KhronosGroup/UnityGLTF/issues/916: humanoid clips used to stay generic (transform curves), so they
	// couldn't be retargeted and the Animator didn't extract root motion from them

	[TestCase(HumanoidArmature)]
	[TestCase(HumanoidMixamo)]
	[TestCase(HumanoidAPose)]
	[TestCase(HumanoidUnrealNames)]
	public void Humanoid_ClipsAreHumanoidClips(string file)
	{
		var path = Import(file, AnimationMethod.MecanimHumanoid);
		var model = LoadModel(path);
		var humanBones = new HashSet<string>(LoadAvatar(path).humanDescription.human.Select(b => b.boneName));
		var animatorProperties = new HashSet<string>(AnimationUtility.GetAnimatableBindings(model, model)
			.Where(b => b.type == typeof(Animator)).Select(b => b.propertyName));

		foreach (var clip in LoadClips(path))
		{
			Assert.IsTrue(clip.humanMotion, $"Clip \"{clip.name}\" should be a humanoid clip");
			var bindings = AnimationUtility.GetCurveBindings(clip);
			foreach (var binding in bindings.Where(b => b.type == typeof(Transform)))
				Assert.IsFalse(humanBones.Contains(binding.path.Split('/').Last()), $"Clip \"{clip.name}\" still has a transform curve for the human bone \"{binding.path}\"");

			var properties = bindings.Where(b => b.type == typeof(Animator)).Select(b => b.propertyName).ToArray();
			foreach (var property in properties)
				Assert.IsTrue(animatorProperties.Contains(property), $"Clip \"{clip.name}\" animates \"{property}\", which isn't a property of the humanoid Animator");
			foreach (var property in new[] { "RootT.x", "RootQ.w", "LeftFootT.y", "RightFootQ.w", "LeftHandT.z", "RightHandQ.x", "Spine Front-Back", "Left Upper Leg Front-Back", "LeftHand.Thumb.1 Stretched" })
				CollectionAssert.Contains(properties, property, $"Clip \"{clip.name}\"");
		}
	}

	[TestCase(HumanoidArmature, true)]
	[TestCase(HumanoidArmature, false)]
	[TestCase(HumanoidMixamo, true)]
	public void Humanoid_RootMotionMovesInstance(string file, bool removeEmptyRoots)
	{
		var path = Import(file, AnimationMethod.MecanimHumanoid, removeEmptyRoots: removeEmptyRoots);
		var (instanceOffset, _) = PlayClip(path, "Walk", 0.9f);

		// Walk moves the hips 1.2m forward in 1s; with root motion that movement is applied to the instance
		Assert.AreEqual(1.08f, instanceOffset.z, 0.02f, $"Root motion should move the instance, but it moved {instanceOffset}");
		Assert.Less(Mathf.Abs(instanceOffset.x), 0.01f, $"The instance should only move forward, but it moved {instanceOffset}");
	}

	[TestCase(HumanoidArmature, "Walk", false)]
	[TestCase(HumanoidArmature, "Idle", false)]
	[TestCase(HumanoidArmature, "Walk", true)]
	[TestCase(HumanoidMixamo, "Walk", false)]
	[TestCase(HumanoidAPose, "Walk", false)]
	// Not Idle for the Unreal names: its avatar has no Chest (Unity's auto mapping skips spine_02), so the chest rotation of Idle can't be played exactly
	[TestCase(HumanoidUnrealNames, "Walk", false)]
	public void Humanoid_ClipPlaysTheOriginalPose(string file, string clipName, bool humanoidFlip)
	{
		// With root motion the instance moves, so the bones are compared in world space: that also covers the body position.
		// Muscle space can't represent every pose exactly (e.g. the arms of the A-pose rig are a few mm off).
		var (maxDistance, worst) = CompareWithGenericImport(file, clipName, humanoidFlip, footIK: false, goalBonesOnly: false);
		Assert.Less(maxDistance, 0.01f, $"The humanoid clip should play the pose of the generic clip, but {worst} is {maxDistance:F4}m off");
	}

	[TestCase(HumanoidArmature, "Walk")]
	[TestCase(HumanoidMixamo, "Idle")]
	[TestCase(HumanoidAPose, "Walk")]
	public void Humanoid_FootIK_KeepsHandsAndFeetInPlace(string file, string clipName)
	{
		// Foot IK (on by default for clip playables and in Timeline) uses the IK goal curves. Without them the feet are
		// pulled up to the body. The knees may still bend differently, since IK doesn't fully stretch the legs.
		var (maxDistance, worst) = CompareWithGenericImport(file, clipName, false, footIK: true, goalBonesOnly: true);
		Assert.Less(maxDistance, 0.005f, $"With Foot IK hands and feet should stay where the clip has them, but {worst} is {maxDistance:F4}m off");
	}

	[Test]
	public void Humanoid_ClipsKeepCurvesOfOtherTransforms()
	{
		var path = Import(HumanoidProps, AnimationMethod.MecanimHumanoid);
		var clips = LoadClips(path);
		AssertClipBindingsResolve(path);

		var walk = clips.Single(c => c.name == "Walk");
		Assert.IsTrue(walk.humanMotion);
		Assert.IsTrue(AnimationUtility.GetCurveBindings(walk).Any(b => b.type == typeof(Transform) && b.path.EndsWith("/Prop") && b.propertyName.StartsWith("m_LocalRotation")),
			"The humanoid Walk clip should keep the rotation curves of the prop, which isn't part of the human skeleton");

		// A clip that doesn't move the skeleton stays generic, so it doesn't lock the body when played on another layer
		var propOnly = clips.Single(c => c.name == "PropOnly");
		Assert.IsFalse(propOnly.humanMotion, "PropOnly doesn't animate the skeleton and should stay generic");
		CollectionAssert.IsEmpty(AnimationUtility.GetCurveBindings(propOnly).Where(b => b.type == typeof(Animator)), "PropOnly shouldn't get muscle curves");
	}

	/// <summary>
	/// Plays a clip of the humanoid import (with root motion) and samples the same clip of a generic import of the file.
	/// Returns the largest distance between the human bones of both, or only between hands and feet.
	/// </summary>
	private static (float maxDistance, string worst) CompareWithGenericImport(string file, string clipName, bool humanoidFlip, bool footIK, bool goalBonesOnly)
	{
		var path = $"{TempFolder}/{file}";
		if (!File.Exists(path)) CopyTestAsset(file, path);
		Reimport(path, AnimationMethod.MecanimHumanoid, humanoidFlip: humanoidFlip);
		var genericPath = $"{TempFolder}/Generic_{file}";
		if (!File.Exists(genericPath)) CopyTestAsset(file, genericPath);
		Reimport(genericPath, AnimationMethod.Mecanim);

		var goalBones = new[] { "LeftFoot", "RightFoot", "LeftHand", "RightHand" };
		var boneNames = LoadAvatar(path).humanDescription.human
			.Where(b => !goalBonesOnly || goalBones.Contains(b.humanName))
			.Select(b => b.boneName).ToArray();

		var clip = LoadClips(path).Single(c => c.name == clipName);
		var genericClip = LoadClips(genericPath).Single(c => c.name == clipName);
		var instance = Object.Instantiate(LoadModel(path));
		var genericInstance = Object.Instantiate(LoadModel(genericPath));
		var graph = PlayableGraph.Create("RigImportTests");
		try
		{
			Transform[] Bones(GameObject go) => boneNames.Select(n => go.GetComponentsInChildren<Transform>(true).First(t => t.name == n)).ToArray();
			var bones = Bones(instance);
			var genericBones = Bones(genericInstance);

			graph.SetTimeUpdateMode(DirectorUpdateMode.Manual);
			var playable = AnimationClipPlayable.Create(graph, clip);
			playable.SetApplyFootIK(footIK);
			AnimationPlayableOutput.Create(graph, "Animation", instance.GetComponent<Animator>()).SetSourcePlayable(playable);
			graph.Play();

			var maxDistance = 0f;
			var worst = "";
			const float step = 1f / 30;
			var frames = Mathf.FloorToInt(clip.length / step);
			for (var frame = 0; frame < frames; frame++)
			{
				// The Animator moves the instance by the root motion of each step, so the clip is played step by step
				graph.Evaluate(frame == 0 ? 0 : step);
				var time = frame * step;
				genericClip.SampleAnimation(genericInstance, time);
				for (var i = 0; i < bones.Length; i++)
				{
					var distance = Vector3.Distance(bones[i].position, genericBones[i].position);
					if (distance <= maxDistance) continue;
					maxDistance = distance;
					worst = $"\"{boneNames[i]}\" at {time:F2}s";
				}
			}
			return (maxDistance, worst);
		}
		finally
		{
			graph.Destroy();
			Object.DestroyImmediate(instance);
			Object.DestroyImmediate(genericInstance);
		}
	}

	#endregion

	#region Runtime import

	[UnityTest]
	public IEnumerator Runtime_Mecanim_WithRootNode_EnablesApplyRootMotion()
	{
		// In the editor, FileLoader expects a path relative to the project, so load the copy in Assets
		var path = Import(RootMotionEmptyRoot, AnimationMethod.Mecanim);
		var options = new ImportOptions
		{
			DataLoader = new FileLoader(Path.GetDirectoryName(path)),
			AnimationMethod = AnimationMethod.Mecanim,
			NonHumanoidRootNodeName = "Root",
		};

		var importer = new GLTFSceneImporter(Path.GetFileName(path), options);
		var task = importer.LoadSceneAsync();
		while (!task.IsCompleted) yield return null;

		var created = importer.CreatedObject;
		try
		{
			Assert.IsNull(task.Exception, task.Exception?.ToString());
			Assert.IsTrue(created);
			var animator = created.GetComponent<Animator>();
			Assert.IsTrue(animator);
			Assert.IsTrue(animator.applyRootMotion);
		}
		finally
		{
			if (created) Object.DestroyImmediate(created);
			importer.Dispose();
		}
	}

	#endregion
}
